import os

# Config
configfile: "config.yaml"

# Get the input and output directories
INPUT_DIR = config["paths"]["input_dir"]
OUTPUT_DIR = config["paths"]["output_dir"]
ENV_DIR = config["paths"]["venv_dir"]
TEMP_DIR = config["paths"]["temp_dir"]
CONTAINER_PATH = config["paths"]["container_path"]
BIG_PROJECT_OUTPUT_DIR = "/projects/dark_science/methylation_binning/article/outputs/nanomotif_v1.1.0" #os.path.realpath("~/outputs/nanomotif_v1.1.0")

# Input samples
SAMPLES=[sample for sample in config['samples']]
EPOCHS=[f"{epoch}" for epoch in range(5, config['epochs_num'], 5)]
#        expand(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}"), sample=SAMPLES, epoch=EPOCHS),

rule all:
    input:
        expand(os.path.join(OUTPUT_DIR,"{sample}","SemiBin2", "bins", "contig_bins.tsv"), sample=SAMPLES),
        expand(os.path.join(OUTPUT_DIR,"{sample}","SemiBin2", "checkm2", "quality_report.tsv"), sample=SAMPLES),
        expand(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "bins"), sample=SAMPLES),
        # expand(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "checkm2", "quality_report.tsv"), sample=SAMPLES),
        # expand(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}", "checkm2", "quality_report.tsv"), sample=SAMPLES, epoch=EPOCHS),

rule semibin_v220:
    conda: "semibin2v220"
    input:
        i = lambda wc: os.path.join(INPUT_DIR, config['samples'][wc.sample]['eukfilt']),
        b = lambda wc: os.path.join(INPUT_DIR, config['samples'][wc.sample]['bam']),
    output:
        dir = directory(os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "bins")),
        #output_bins = directory(os.path.join(OUTPUT_DIR, "{wildcards.sample}", "SemiBin2", "bins", "output_bins")),
        #data = os.path.join(OUTPUT_DIR, "{wildcards.sample}", "SemiBin2", "bins", "data.csv"),
        contig_bins = os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "bins", "contig_bins.tsv"),
    params:
        min_contig_len = config["filtering"]["min_contig_len"],
        sequencing_type = "long_read",
        epochs_num = config["epochs_num"],
        semibin2_path = os.path.join(ENV_DIR, "semibin2v220", "bin", "SemiBin2"),
        container_path = os.path.join(CONTAINER_PATH, ),
    resources:
        mem="100G",
        threads = 40,
        walltime="1-00:00:00",
        nodetype=config["partitions"]["cpu"],
    shell:
        r"""
        echo {output.dir}

        if [[ -d {BIG_PROJECT_OUTPUT_DIR}/{wildcards.sample} ]]; then

            mkdir -p {output.dir}
            ln -s {BIG_PROJECT_OUTPUT_DIR}/{wildcards.sample}/SemiBin2/bins/* {output.dir}/

        else

            echo {input.i}

        fi
        """
        #else
        #    which {params.semibin2_path} & \
        #    apptainer exec --bind /projects:/projects {params.container_path} \
        #        {params.semibin2_path} single_easy_bin \
        #        --input-fasta {input.i} \
        #        -b {input.b} \
        #        -o {output.dir} \
        #        -m {params.min_contig_len} \
        #        --sequencing-type {params.sequencing_type} \
        #        -p {resources.threads}
        #fi
        

rule checkm2_semibin2:
    conda: 
       "checkm2_v1.1.0",
    input:
        output_bins = os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "bins", "output_bins"),
    output:
        dir = directory(os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "checkm2")),
        quality_file = os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "checkm2", "quality_report.tsv"),
    params:
        ext = ".fa",
        db = config["databases"]["checkm2"],
        checkm2 = config["paths"]["checkm2"],
    resources:
        mem = "64G",
        threads = 16,
        walltime = "1-00:00:00",
        nodetype = config["partitions"]["cpu"],
    shell:
        r"""
        if [[ -d {BIG_PROJECT_OUTPUT_DIR}/{wildcards.sample} ]]; then
            echo {output.quality_file}
            mkdir -p {output.dir}
            ln -s {BIG_PROJECT_OUTPUT_DIR}/{wildcards.sample}/SemiBin2/checkm2/* {OUTPUT_DIR}/{wildcards.sample}/SemiBin2/checkm2/

        else

            CHECKM2DB={params.db};
            checkm2 predict \
                -i {input.output_bins}/* \
                -o {output.dir} \
                -x {params.ext} \
                -t {resources.threads} \
                --force

        fi        
        """

rule refining1_train:
    conda: "semibinrefining"
    input:
        data = os.path.join(OUTPUT_DIR, "{sample}", "SemiBin2", "bins", "data.csv"),
        data_split = os.path.join(OUTPUT_DIR,"{sample}","SemiBin2","bins","data_split.csv"),
        contig_bins = os.path.join(OUTPUT_DIR,"{sample}","SemiBin2","bins","contig_bins.tsv"),
        quality_bins = os.path.join(OUTPUT_DIR,"{sample}","SemiBin2","checkm2","quality_report.tsv"),
    output:
        dir = directory(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "bins")),
    params:
        semibin_path = os.path.join(ENV_DIR, "semibinrefining", "bin", "SemiBin2"),
        container_path = os.path.join(CONTAINER_PATH, ),
    resources:
        mem="96G",
        threads = 10,
        walltime="1-00:00:00",
        nodetype=config["partitions"]["cpu"],
    shell:
        r"""
        which {params.semibin_path};
        apptainer exec --bind /projects:/projects {params.container_path} {params.semibin_path} train_self \
            --data {input.data} \
            --data-split {input.data_split} \
            --contig_bins_file {input.contig_bins} \
            --quality_report_file {input.quality_bins} \
            --threads {resources.threads} \
            --engine cpu \
            --output {output.dir} 
        """


# rule semibin_binning:
#     conda: "semibiniclr"
#     wildcard_constraints:
#         epoch = r"[0-9]+"
#     input:
#         i = lambda wildcards: os.path.join(INPUT_DIR, config['samples'][wildcards.sample]['eukfilt']),
#         data = os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "bins", "data.csv"),
#         model = os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "bins", "checkpoint_{epoch}.pt"),
#     output:
#         dir = directory(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}", "output_bins")),
#     params:
#         semibin2_path = os.path.join(ENV_DIR, "semibiniclr", "bin", "SemiBin2"),
#         container_path = os.path.join(CONTAINER_PATH, ),
#     resources:
#         mem="32G",
#         threads = 10,
#         walltime="1-00:00:00",
#         nodetype=config["partitions"]["cpu"],
#     shell:
#         """
#         which {params.semibin2_path} & \
#         apptainer exec --bind /projects:/projects {params.container_path} {params.semibin2_path} bin_long \
#             --input-fasta {input.i} \
#             --data {input.data} \
#             --model {input.model} \
#             --output {output.dir} \
#             -p {resources.threads}
#         """
#
# rule checkm2_semibin2:
#     conda:
#        "checkm2_v1.1.0",
#     wildcard_constraints:
#         epoch = r"[0-9]+"
#     input:
#         output_bins = os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}", "output_bins", "output_bins"),
#     output:
#         dir = directory(os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}", "checkm2")),
#         quality_file = os.path.join(OUTPUT_DIR, "{sample}", "SemiBinICLR", "epoch_{epoch}", "checkm2", "quality_report.tsv"),
#     params:
#         ext = ".fa",
#         db = config["databases"]["checkm2"],
#         checkm2 = config["paths"]["checkm2"],
#     resources:
#         mem = "64G",
#         threads = 16,
#         walltime = "1-00:00:00",
#         nodetype = config["partitions"]["cpu"],
#     shell:
#         """
#         CHECKM2DB={params.db}
#         checkm2 predict \
#             -i {input.output_bins}/* \
#             -o {output.dir} \
#             -x {params.ext} \
#             -t {resources.threads} \
#             --force
#         """

